version: '3.1'
services:
  postgres:
    image: postgres:13-alpine
    restart: always
    command:
      - 'postgres'
      - '-c'
      - 'max_connections=100'
      - '-c'
      - 'shared_buffers=256MB'
    environment:
      POSTGRES_DB: bsdb
      POSTGRES_USER: bsuser
      POSTGRES_PASSWORD: bspw
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

#  nginx:
#    restart: always
#    build:
#      dockerfile: Dockerfile.dev
#      context: ./nginx
#    ports:
#      - '3050:80'

volumes:
  postgres:
    driver: local
